name: Hourly Exhibition Details

on:
  schedule:
    - cron: '0 1-5 * * *'  # JST 10〜14時 (UTC 1〜5時)
  workflow_dispatch:

jobs:
  post_detail_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requests
        run: pip install -r config/requirements.txt

      - name: Run one detail post
        run: python src/post_exhibition_info.py detail
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}

      - name: Commit and Push Detail History Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git add data/detail_history.json

          if ! git diff --staged --quiet; then
            git commit -m "Update detail history $(date +'%Y-%m-%d %H:%M:%S %Z')"
            git push
          else
            echo "No changes in detail history to commit."
          fi
