name: Hourly Exhibition Details

on:
  schedule:
    - cron: '0 1-5 * * *'  # JST 10〜14時 (UTC 1〜5時)
  workflow_dispatch:

jobs:
  post_detail_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requests
        run: pip install requests

      - name: Run one detail post
        run: python post_exhibition_info.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}
          MODE: detail
