name: LINE Auto Tweet

on:
  workflow_dispatch:  # 手動実行
  
  schedule:
    - cron: '0 0,3,6,9,12 * * *'
  
jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Send LINE message
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}
      run: python send2line.py

    - name: Commit and push updates
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
        git pull --rebase --autostash  # 自動的に変更を退避しながらリベース
        git add -A  # すべての新規 & 変更ファイルを追加
        git commit -m "Update topics and logs" || echo "Nothing to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

